title: Alice&#39;s Awesome Blog
description: "Hi, I'm Alice Perez"
tagline: "My tech journey transitioning from sales to engineering"
sass:
  sass_dir: assets/sass
url: aperez25.github.io
github_username: aperez25
linkedin_username: alicep
feed_icon:
email: "alice.perez25[at]gmail.com"
gems: [jekyll-paginate, jekyll-feed]
paginate_path: "/page/:num/"
paginate: 5
