title: Strata by HTML5 UP
description: >
  Alice Perez
sass:
  sass_dir: assets/sass
url: http://localhost:4000
facebook_username:
twitter_username: "#"
github_username:  "aperez25"
linkedin_username: "#"
feed_icon: rss
email: "alice.perez25[at]gmail.com"
gems: -jekyll-paginate
	-jekyll-feed
paginate_path: "/page/:num/"
paginate: 5
